version: '3'
services:
    httpd:
        image: httpd:2.4.49
        volumes:
        - ./htdocs:/usr/local/apache2/htdocs
        - ./httpd.conf:/usr/local/apache2/conf/httpd.conf
        ports:
        - 8000:80
